- hosts: all
  vars:
    dokku_version: 0.11.3
    install_dokku_script: |
      echo "{{ lookup('env', 'SSH_PUBLIC_KEY') }}" > key.pub
      DOKKU_TAG=v{{ dokku_version }} DOKKU_WEB_CONFIG=false DOKKU_KEY_FILE="$(pwd)/key.pub" bash install-dokku.sh
      echo "installed dokku"
      touch dokku-{{ dokku_version }}-installed
      creates=dokku-{{ dokku_version }}-installed
  tasks:
    - get_url:
        url: https://raw.githubusercontent.com/dokku/dokku/v{{ dokku_version }}/bootstrap.sh
        dest: "./install-dokku.sh"
    - shell: "{{ install_dokku_script }} become=true"
