- hosts: all
  vars:
    dokku_version: 0.11.3
    dokku_public_key_file: "{{ansible_env.HOME}}/dokku_key.pub"
    install_dokku: "{{ansible_env.HOME}}/install-dokku-{{dokku_version}}"
  tasks:
    - get_url:
        url: https://raw.githubusercontent.com/dokku/dokku/v{{dokku_version}}/bootstrap.sh
        dest: "{{install_dokku}}"
    - file:
        path: "{{install_dokku}}"
        mode: u+x
    - command: dokku version
      register: dokku_version_result
      changed_when: false
      failed_when: dokku_version_result.rc != 0 and dokku_version_result.rc != 2
    - command: "{{install_dokku}}"
      register: install_dokku_result
      changed_when: install_dokku_result | succeeded
      become: true
      when: dokku_version_result.rc == 2 or dokku_version not in dokku_version_result.stdout
      environment:
        DOKKU_TAG: v{{dokku_version}}
        DOKKU_WEB_CONFIG: "false"
        DOKKU_SKIP_KEY_FILE: "true"
    - copy:
        content: "{{lookup('env', 'SSH_PUBLIC_KEY')}}"
        dest: "{{dokku_public_key_file}}"
    - command: ssh-keygen -l -f {{dokku_public_key_file}}
      register: ssh_keygen_result
      changed_when: false
    - command: dokku ssh-keys:list
      register: dokku_keys_result
      changed_when: false
      failed_when: dokku_keys_result.rc != 0 and "No public keys found" not in dokku_keys_result.stderr
    - command: bash -c 'dokku ssh-keys:add admin {{dokku_public_key_file | quote}} < /dev/null'
      register: dokku_add_key_result
      changed_when: dokku_add_key_result | succeeded
      become: true
      when: "'%s NAME=\"admin\"' % ssh_keygen_result.stdout.split(' ')[1] not in dokku_keys_result.stdout"
